# Generated by Django 3.1.7 on 2022-02-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dog_id', models.IntegerField(unique=True)),
                ('color', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('birth', models.DateField(blank=True, null=True)),
                ('sire', models.CharField(blank=True, default='Not informed', max_length=255, null=True)),
                ('dam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.BigIntegerField(unique=True)),
                ('distance', models.IntegerField()),
                ('grade', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('post_pick', models.CharField(blank=True, max_length=255, null=True)),
                ('tipdetails', models.CharField(blank=True, max_length=255, null=True)),
                ('sportinglife', models.CharField(blank=True, max_length=255, null=True)),
                ('timeform', models.CharField(blank=True, max_length=255, null=True)),
                ('tipdetails_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='replays')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrackStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('trap1', models.IntegerField(default=0)),
                ('trap2', models.IntegerField(default=0)),
                ('trap3', models.IntegerField(default=0)),
                ('trap4', models.IntegerField(default=0)),
                ('trap5', models.IntegerField(default=0)),
                ('trap6', models.IntegerField(default=0)),
                ('female', models.IntegerField(default=0)),
                ('male', models.IntegerField(default=0)),
                ('avg_weight', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyhound.dog')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traps', to='greyhound.race')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placing', models.CharField(max_length=2)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyhound.race')),
                ('trap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyhound.trap')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyhound.track'),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_speed', models.IntegerField(default=0)),
                ('best_real_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecast', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('best_real_time_grade', models.CharField(max_length=4, null=True)),
                ('best_real_time_date', models.DateField(null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('reserve', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('date_of_season', models.DateField(null=True)),
                ('type_of_season', models.CharField(blank=True, max_length=25, null=True)),
                ('handicap', models.CharField(blank=True, max_length=10, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyhound.dog')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyhound.race')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyhound.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.IntegerField(null=True)),
                ('distance', models.IntegerField()),
                ('grade', models.CharField(max_length=4)),
                ('date', models.DateTimeField()),
                ('winner_time', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('going', models.CharField(blank=True, max_length=4, null=True)),
                ('trap', models.IntegerField(blank=True, null=True)),
                ('split', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bends', models.CharField(blank=True, max_length=4, null=True)),
                ('placing', models.IntegerField(blank=True, null=True)),
                ('odds_frctn_numer', models.IntegerField(blank=True, null=True)),
                ('odds_frctn_denom', models.IntegerField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyhound.dog')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greyhound.race')),
            ],
        ),
    ]
